### ISSUE TITLE
Add support for release-it 17

### ISSUE THREAD

**Issue by j-ulrich** [j-ulrich/release-it-regex-bumper#11]
release-it 17 was released a few days ago: https://github.com/release-it/release-it/releases/tag/17.0.0

We need to add support for it.

**Comment by muuvmuuv** [comment]
It seems to work without modifications, so maybe just bumb peers?

**Comment by j-ulrich** [comment]
Fixed in version [5.1.0](https://github.com/j-ulrich/release-it-regex-bumper/releases/tag/5.1.0).
